### ISSUE TITLE
Spatial method changes get_rotation_deg set_rotation_deg

### ISSUE THREAD

**Issue by hungrymonkey** [satyries/Pama#1]
https://github.com/godotengine/godot/commit/482e07af7e5c8b85463f950036dc7b14cb8cd3b4#diff-43287f78e603b193c1c77b7298273367L682

I just want to gives you an heads up, it seems like they rename a method upstream. 

Spatial class 

get_rotation_deg -> get_rotation_degrees
set_rotation_deg -> set_rotation_degrees

**Comment by satyries** [comment]
Sorry for the latency, it looks like I've missed the notification. I've update the method; thanks for the report! :+1:
